# - env:
#     deployment:
#       type: docker
#       image: a11y/tailwindcss:latest
#     repo:
#       type: preexisting
#       repo_name: app
#   problem_statement:
#     type: text_file
#     path: problem_statement_tailwind_blog.txt
#     id: tailwindcss-blog

# - env:
#     deployment:
#       type: docker
#       image: a11y/tailwindcss:latest
#     repo:
#       type: preexisting
#       repo_name: app
#   problem_statement:
#     type: text_file
#     path: problem_statement_tailwind_docs_installation_using-vite.txt
#     id: tailwindcss-docs-installation-using-vite

# - env:
#     deployment:
#       type: docker
#       image: a11y/typescript-website:latest
#     repo:
#       type: preexisting
#       repo_name: app
#   problem_statement:
#     type: text_file
#     path: problem_statement_typescript_tools.txt
#     id: typescript-website-tools

# - env:
#     deployment:
#       type: docker
#       image: a11y/typescript-website:latest
#     repo:
#       type: preexisting
#       repo_name: app
#   problem_statement:
#     type: text_file
#     path: problem_statement_typescript_play.txt
#     id: typescript-website-play

# - env:
#     deployment:
#       type: docker
#       image: a11y/typescript-website:latest
#     repo:
#       type: preexisting
#       repo_name: app
#   problem_statement:
#     type: text_file
#     path: problem_statement_typescript_homepage.txt
#     id: typescript-website-homepage

# - env:
#     deployment:
#       type: docker
#       image: a11y/typescript-website:latest
#     repo:
#       type: preexisting
#       repo_name: app
#   problem_statement:
#     type: text_file
#     path: problem_statement_typescript_download.txt
#     id: typescript-website-download

- env:
    deployment:
      type: docker
      image: a11y/typescript-website:latest
    repo:
      type: preexisting
      repo_name: app
  problem_statement:
    type: text_file
    path: problem_statement_typescript_docs_handbook.txt
    id: typescript-website-docs-handbook

# - env:
#     deployment:
#       type: docker
#       image: a11y/typescript-website:latest
#     repo:
#       type: preexisting
#       repo_name: app
#   problem_statement:
#     type: text_file
#     path: problem_statement_typescript_community.txt
#     id: typescript-website-community